### PR TITLE
Add typescript types

### PR DESCRIPTION
**Pull request by is343**

### CODE REVIEW

**Comment by leMaik** [comment]
Thank you for your first contribution, @is343! :tada:
I'll merge this and publish a new release soon (TM).

**Comment by naiveai** [comment]
Hey, sorry to bother you on this, but is there a blocker on this? Seems so far the only issue is that `StandardProps` requires generic type arguments, @is343.

**Comment by is343** [comment]
The typing works for this the last time I used it. No need to pass any generics. 
This should be good to go. I'm guessing there still hasn't been any new release. @naiveai

**Comment by leMaik** [comment]
Sorry for the delay and thanks again @is343 :)

**Comment by leMaik** [comment]
Published as v1.1.1 :rocket:

**Comment by khellang** [comment]
Hello @leMaik!

How are the types supposed to work, exactly? I'm getting the following with v1.1.1:

> Could not find a declaration file for module 'material-ui-toggle-icon'. './node_modules/material-ui-toggle-icon/lib/ToggleIcon.js' implicitly has an 'any' type.

I see that `package.json` has

https://github.com/TeamWertarbyte/material-ui-toggle-icon/blob/e0d414010c4dba61abe8a945f431d6578062460b/package.json#L5-L6

But in my extracted module, I can't see any typings in the `lib` folder:

image

Could it be that the types aren't being copied over to the `lib` folder?

**Comment by khellang** [comment]
It looks like copying the `.d.ts` file over to the `lib` folder worked. Would be awesome with a new version with that 🙏🏻

**Comment by leMaik** [comment]
@khellang Whoops… I never look into my notifications and only really see _new_ issues when they are created. Anyway, v1.1.2 fixes this :+1:

**Pull request merged**
